IF COL_LENGTH('[dbo].[QueueItems]', 'ProcessingExceptionDetails') IS NOT NULL 
AND 'Nvarchar' IN (
	SELECT DATA_TYPE FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_NAME = 'QUEUEITEMS' 
		AND TABLE_SCHEMA = 'DBO' 
		AND COLUMN_NAME = 'PROCESSINGEXCEPTIONDETAILS'
)
BEGIN
	ALTER TABLE [dbo].[QueueItems]
	ALTER COLUMN ProcessingExceptionDetails NVARCHAR(MAX)
END